apiVersion: v2
name: cdp-forge
description: A Helm chart for CDP Forge
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - cdp
  - cdpforge
home: https://github.com/your-org/cdp-forge
sources:
  - https://github.com/your-org/cdp-forge
maintainers:
  - name: CDP Team
    email: cdp-team@example.com

dependencies:
  - name: redis
    version: 21.2.13
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mysql
    version: 9.14.2
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: opensearch
    version: 3.1.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.enabled
  - name: opensearch-dashboards
    version: 3.1.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch-dashboards.enabled
  - name: pulsar
    version: 4.1.0
    repository: https://pulsar.apache.org/charts
    condition: pulsar.enabled