global:
  environment: development
  domain: cdp-forge-dev.local

# Configurazione Cluster Pulsar
pulsar:
  affinity:
    anti_affinity: false

  zookeeper:
    affinity:
      anti_affinity: false
    volumes:
      data:
        size: 5Gi

  bookkeeper:
    replicaCount: 3
    affinity:
      anti_affinity: false
    volumes:
      # use a persistent volume or emptyDir
      persistence: true
      journal:
        name: journal
        size: 5Gi
        local_storage:
          storageClassName: local-path
      ledgers:
        size: 10Gi
        local_storage:
          storageClassName: local-path
  autorecovery:
    affinity:
      anti_affinity: false

  broker:
    affinity:
      anti_affinity: false
    resources:
      requests:
        memory: 512Mi
        cpu: 0.2

  proxy:
    replicaCount: 1
    affinity:
      anti_affinity: false

  pulsar_manager:
    admin:
      existingSecret: ""
      ui_username: "pulsar"
      ui_password: "cdpforge"  # leave empty for random password
      db_username: "pulsar"
      db_password: "cdpforge"  # leave empty for random password

# Configurazione OpenSearch Helm Chart
opensearch:
  enabled: true
  
  # Configurazione cluster
  clusterName: "cdp-forge-opensearch"
  
  # Configurazione nodo singolo con tutti i ruoli
  nodeGroup: "master"
  replicas: 1
  
  # Ruoli del nodo (tutti i ruoli in un singolo nodeGroup)
  roles:
    - master
    - ingest
    - data
    - remote_cluster_client
  
  # Configurazione risorse
  resources:
    requests:
      memory: "1Gi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "400m"
  
  # Configurazione persistenza
  persistence:
    enabled: true
    size: 1Gi
  
  # Variabili d'ambiente aggiuntive per OpenSearch 3.1.0
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: "CdpForge@2024!"

# Configurazione OpenSearch Dashboards
opensearch-dashboards:
  enabled: true
  
  # Configurazione risorse
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  
  # Configurazione servizio
  service:
    type: ClusterIP
    port: 5601
  
  # Configurazione sicurezza
  security:
    adminPassword: "CdpForge@2024!"

mysql:
  architecture: standalone
  enabled: true
  
  # Configurazione autenticazione
  auth:
    rootPassword: "cdp-forge-root-2024"
    database: "cdpforge"
    username: "cdp_forge_user"
    password: "cdp-forge-user-2024"
  
  # Configurazione inizializzazione database con Flyway
  init:
    enabled: true
    flyway:
      enabled: true
      repository: "https://github.com/CDPForge/core-mysql.git"
      version: "9.22.3"
  
  # Configurazione replicazione
  primary:
    enabled: true
    persistence:
      enabled: true
      size: 1Gi
      storageClass: ""
    resources:
      requests:
        memory: "1Gi"
        cpu: "100m"
      limits:
        memory: "2Gi"
        cpu: "400m"
    service:
      type: ClusterIP
      port: 3306

  secondary:
    enabled: false
    replicaCount: 0
  
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
  
  backup:
    enabled: false

# Configurazione Core Pipeline Manager
core-pipeline-manager:
  # Configurazione risorse
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

plugin-pipeline-geo:
  geoDbtoken: "UUK9XaaTqwGd3xWUo3oRAxCLjZauqAn58IhsU4QyfOFs3Xt22EvcvLh62o3ZsDnX"
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"