{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cdp-forge.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cdp-forge.fullname" . }}-ca-issuer
spec:
  ca:
    secretName: {{ include "cdp-forge.fullname" . }}-ca-key-pair
    secretNamespace: {{ .Release.Namespace }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cdp-forge.fullname" . }}-ca-certificate
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ include "cdp-forge.fullname" . }}-ca
  secretName: {{ include "cdp-forge.fullname" . }}-ca-key-pair
  issuerRef:
    name: {{ include "cdp-forge.fullname" . }}-selfsigned-issuer
    kind: ClusterIssuer
{{- end }}