{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cdp-forge.fullname" . }}-selfsigned-issuer
  labels:
    {{- include "cdp-forge.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cdp-forge.fullname" . }}-ca-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cdp-forge.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ include "cdp-forge.fullname" . }}-ca
  secretName: {{ include "cdp-forge.fullname" . }}-ca-key-pair
  duration: {{ .Values.certmanager.caDuration | default "8760h" }}
  renewBefore: {{ .Values.certmanager.caRenewBefore | default "720h" }}
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: {{ include "cdp-forge.fullname" . }}-selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cdp-forge.fullname" . }}-ca-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cdp-forge.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "cdp-forge.fullname" . }}-ca-key-pair
{{- end }}