{{- if and .Values.certmanager.enabled .Values.opensearch.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-certs
  namespace: {{ .Release.Namespace }}
spec:
  secretName: opensearch-certs
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: {{ include "cdp-forge.fullname" . }}-ca-issuer
    kind: Issuer
  commonName: cdp-forge-opensearch-cluster-master
  dnsNames:
    - cdp-forge-opensearch-cluster-master
    - cdp-forge-opensearch-cluster-master.{{ .Release.Namespace }}.svc
    - cdp-forge-opensearch-cluster-master.{{ .Release.Namespace }}.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
  duration: 8760h # 1 anno
  renewBefore: 720h # rinnova 30 giorni prima
{{- end }}