{{- if (index .Values "phpmyadmin").enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pma-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
{{- end }}
