{{- if (index .Values "phpmyadmin").enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pma
  labels:
    app: {{ .Release.Name }}-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-phpmyadmin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: {{ .Release.Name }}-mysql
            - name: PMA_PORT
              value: "3306"
{{- end }}
