{{- if (index .Values "core-input").enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cdp-forge.fullname" . }}-core-input
  labels:
    {{- include "cdp-forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: core-input
spec:
  type: {{ (index .Values "core-input").service.type }}
  ports:
    - port: {{ (index .Values "core-input").service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "cdp-forge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core-input
{{- end }}
