{{- if (index .Values "core-input").enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cdp-forge.fullname" . }}-core-input
  labels:
    {{- include "cdp-forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: core-input
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cdp-forge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: core-input
  template:
    metadata:
      labels:
        {{- include "cdp-forge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: core-input
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000

      containers:
      - name: core-input
        image: ghcr.io/cdpforge/core-input:{{ (index .Values "core-input").image.tag | default "latest" }}
        imagePullPolicy: {{ (index .Values "core-input").image.pullPolicy | default "IfNotPresent" }}
        envFrom:
          - secretRef:
              name: {{ include "cdp-forge.fullname" . }}-cluster-config

        ports:
        - name: http
          containerPort: 3000
          protocol: TCP

        {{- if (index .Values "core-input").resources }}
        resources:
          {{- toYaml (index .Values "core-input").resources | nindent 10 }}
        {{- end }}
{{- end }}
