{{- if or .Values.kafka.enabled .Values.opensearch.enabled .Values.mysql.enabled }}
{{- $opensearchPassword := "" }}
{{- if .Values.opensearch.enabled }}
  {{- range .Values.opensearch.extraEnvs }}
    {{- if eq .name "OPENSEARCH_INITIAL_ADMIN_PASSWORD" }}
      {{- $opensearchPassword = .value }}
    {{- end }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdp-forge.fullname" . }}-cluster-config
  labels:
    {{- include "cdp-forge.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yml: |-
    {{- if .Values.kafka.enabled }}
    kafkaConfig:
      brokers:
        - "{{ .Values.kafka.name }}-kafka-bootstrap:9092"
    {{- end }}

    {{- if .Values.mysql.enabled }}
    mysqlConfig:
      uri: "mysql://root:{{ .Values.mysql.auth.rootPassword }}@{{ .Release.Name }}-mysql-primary:3306/{{ .Values.mysql.auth.database }}"
    {{- end }}

    {{- if .Values.opensearch.enabled }}
    esConfig:
      url: "http://{{ .Values.opensearch.clusterName }}-master:9200"
      username: "admin"
      password: "{{ $opensearchPassword }}"
    {{- end }}
{{- end }}