{{- if or .Values.pulsar.enabled .Values.opensearch.enabled .Values.mysql.enabled }}
{{- $opensearchPassword := "" }}
{{- if .Values.opensearch.enabled }}
  {{- range .Values.opensearch.extraEnvs }}
    {{- if eq .name "OPENSEARCH_INITIAL_ADMIN_PASSWORD" }}
      {{- $opensearchPassword = .value }}
    {{- end }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdp-forge.fullname" . }}-cluster-config
  labels:
    {{- include "cdp-forge.labels" . | nindent 4 }}
type: Opaque
stringData:
  PIPELINEMANAGER_FIRST_TOPIC: "logs"

  {{- if .Values.pulsar.enabled }}
  PULSAR_PROXY: "pulsar://{{ .Release.Name }}-pulsar-proxy:6650"
  PULSAR_UI_PASSWORD: {{ .Values.pulsar.pulsar_manager.admin.ui_password }}
  PULSAR_DB_PASSWORD: {{ .Values.pulsar.pulsar_manager.admin.db_password }}
  {{- end }}

  {{- if .Values.mysql.enabled }}
  MYSQL_URI: "mysql://root:{{ .Values.mysql.auth.rootPassword }}@{{ .Release.Name }}-mysql:3306/{{ .Values.mysql.auth.database }}"
  {{- end }}

  {{- if .Values.opensearch.enabled }}
  OPENSEARCH_URL: "https://{{ .Release.Name }}-opensearch-cluster-master:9200"
  OPENSEARCH_USERNAME: "admin"
  OPENSEARCH_PASSWORD: "{{ $opensearchPassword }}"
  {{- end }}

  {{- if (index .Values "core-pipeline-stage").enabled }}
  PIPELINEMANAGER_CONFIG_TOPIC: "config"
  PIPELINEMANAGER_URL: "http://{{ .Release.Name }}-core-pipeline-manager"
  {{- end}}

  {{- if (index .Values "plugin-pipeline-geo").enabled }}
  GEO_DBTOKEN: "{{ (index .Values "plugin-pipeline-geo").geoDbtoken }}"
  {{- end}}

  {{- if .Values.redis.enabled }}
  REDIS: {{ .Release.Name }}-redis-master
  REDIS_PASSWORD: {{ .Values.redis.password }}
  {{- end }}
{{- end }}