apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name | default "my-cluster" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    strimzi.io/kraft: "enabled"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: {{ .Values.kafka.version | default "3.9.0" }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      {{- if .Values.kafka.advertiseLocalhost }}
      - configuration: # TO CONNECT FROM LOCAL DEV ENV LIKE DOCKER DESKTOP
          brokers:
            - advertisedHost: localhost
              broker: 0
            - advertisedHost: localhost
              broker: 1
            - advertisedHost: localhost
              broker: 2
        name: external
        port: 9094
        tls: false
        type: nodeport
      {{- end }}

  entityOperator:
    topicOperator: {}
    userOperator: {} 