{{- if (index .Values "plugin-pipeline-geo").enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cdp-forge.fullname" . }}-plugin-pipeline-geo
  labels:
    {{- include "cdp-forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-pipeline-geo
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cdp-forge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: plugin-pipeline-geo
  template:
    metadata:
      labels:
        {{- include "cdp-forge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: plugin-pipeline-geo
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000

      initContainers:
        {{- if (index .Values "core-pipeline-manager").enabled }}
        - name: wait-for-core-pipeline-manager
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z cdp-forge-core-pipeline-manager 80; do echo waiting for core-pipeline-manager; sleep 2; done;']
        {{- end }}

      containers:
      - name: plugin-pipeline-geo
        image: ghcr.io/cdpforge/plugin-pipeline-geo:{{ (index .Values "plugin-pipeline-geo").image.tag | default "latest" }}
        imagePullPolicy: {{ (index .Values "plugin-pipeline-geo").image.pullPolicy | default "IfNotPresent" }}
        envFrom:
          - secretRef:
              name: {{ include "cdp-forge.fullname" . }}-cluster-config

        ports:
        - name: http
          containerPort: 3000
          protocol: TCP

        {{- if (index .Values "plugin-pipeline-geo").resources }}
        resources:
          {{- toYaml (index .Values "plugin-pipeline-geo").resources | nindent 10 }}
        {{- end }}
{{- end }}
