{{- if (index .Values "plugin-pipeline-output").enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cdp-forge.fullname" . }}-plugin-pipeline-output
  labels:
    {{- include "cdp-forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-pipeline-output
spec:
  type: {{ (index .Values "plugin-pipeline-output").service.type }}
  ports:
    - port: {{ (index .Values "plugin-pipeline-output").service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "cdp-forge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-pipeline-output
{{- end }}
